Repository openstack-k8s-operators/heat-operator, pull requests merged in 2023-04, with the labels that each got.

#53 Update operator metadata
  config/manifests/bases/heat-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#56 Fix some CRs not being installed
  config/crd/kustomization.yaml
Labels: approved, lgtm

#57 Fix a missing CRDs in operator manifest
  config/manifests/bases/heat-operator.clusterserviceversion.yaml
Labels: approved

#54 Fix missing RBAC rules
  config/rbac/role.yaml
  controllers/heat_controller.go
  controllers/heatapi_controller.go
  controllers/heatengine_controller.go
Labels: approved, lgtm

#55 Extend timeout in golangci-lint
  .golangci.yaml
  Makefile
Labels: approved, lgtm

#60 Update manifests
  config/rbac/role.yaml
Labels: approved, lgtm

#59 Add kuttl tests for Heat
  kuttl-test.yaml
  tests/kuttl/tests/basic/01-assert.yaml
  tests/kuttl/tests/basic/01-deploy-heat.yaml
  tests/kuttl/tests/common/assert-sample-deployment.yaml
Labels: approved, lgtm

#65 Squash config files into a single layer
  controllers/heat_controller.go
  controllers/heatapi_controller.go
  controllers/heatengine_controller.go
  templates/heat/config/heat-api-httpd.conf
  templates/heat/config/heat-engine-config.json
  templates/heat/config/heat.conf
  templates/heat/config/heatapi-config.json
  templates/heatapi/config/heat.conf
  templates/heatengine/config/heat.conf
Labels: approved, lgtm

#72 Add renovate.json / Remove dependabot.yml
  .github/dependabot.yml
  renovate.json
Labels: approved, lgtm

#73 [renovate] run go mod tidy for both mod files
  Makefile
  api/go.mod
  api/go.sum
  renovate.json
Labels: approved, lgtm

#66 Replace TripleO images by TCIB images
  api/v1beta1/heatapi_types.go
  api/v1beta1/heatengine_types.go
  config/crd/bases/heat.openstack.org_heatapis.yaml
  config/crd/bases/heat.openstack.org_heatengines.yaml
  config/crd/bases/heat.openstack.org_heats.yaml
  config/samples/heat_v1beta1_heat.yaml
  tests/kuttl/tests/common/assert-sample-deployment.yaml
Labels: approved, lgtm

#67 Simplify heat.conf
  templates/heat/config/heat.conf
Labels: approved

#75 Add initial docs
  README.md
Labels: approved

#76 Remove unused bootstrap debug flag
  README.md
  api/v1beta1/heat_types.go
  config/crd/bases/heat.openstack.org_heatapis.yaml
  config/crd/bases/heat.openstack.org_heatengines.yaml
  config/crd/bases/heat.openstack.org_heats.yaml
  config/samples/heat_v1beta1_heat.yaml
  tests/kuttl/tests/common/assert-sample-deployment.yaml
Labels: approved, lgtm

#79 Disable log file and use stderr for log output
  templates/heat/config/db-sync-config.json
  templates/heat/config/heat-engine-config.json
  templates/heat/config/heat.conf
  templates/heat/config/heatapi-config.json
Labels: approved, lgtm

#77 Enable ginkgolinter
  .golangci.yaml
Labels: approved, lgtm

#78 Remove install_yamls dependency for kuttl tests
  kuttl-test.yaml
  tests/kuttl/tests/basic/01-assert.yaml
  tests/kuttl/tests/basic/01-deploy-heat.yaml
Labels: lgtm

#88 Fix default IMAGE_TAG_BASE
  Makefile
Labels: approved, lgtm

#85 Remove non-existing rpcTransport spec
  tests/kuttl/tests/common/assert-sample-deployment.yaml
Labels: approved, lgtm

#87 Fix a few descriptions mentioning wrong service
  api/v1beta1/heat_types.go
  config/crd/bases/heat.openstack.org_heats.yaml
Labels: approved, lgtm

#86 Use specific secret keys by default
  README.md
  api/v1beta1/heat_types.go
  api/v1beta1/heatapi_types.go
  api/v1beta1/heatengine_types.go
  config/crd/bases/heat.openstack.org_heatapis.yaml
  config/crd/bases/heat.openstack.org_heatengines.yaml
  config/crd/bases/heat.openstack.org_heats.yaml
  config/samples/heat_v1beta1_heat.yaml
  tests/kuttl/tests/common/assert-sample-deployment.yaml
Labels: approved, lgtm

#92 Fix typos in template parameters
  controllers/heat_controller.go
Labels: approved, lgtm

#82 Wrap errors when returning them
  controllers/heat_controller.go
  controllers/heatapi_controller.go
Labels: approved, lgtm
